### PR TITLE
Add the extra properties to OperationalUnit

### PR DESCRIPTION
**Pull request by lionslair**
There appears to be new properties on the OperationUnit model that are missing. 

`$workType` and `$operationalUnitType` is documented https://developer.deputy.com/deputy-docs/docs/operational-unit-1 however `$companyName` and  `$companyCode` are just present.

Copy of returned api call for reference

```json

[
  {
    "Id": 16,
    "Creator": 1,
    "Created": "2023-05-25T11:46:44+08:00",
    "Modified": "2023-05-25T11:46:44+08:00",
    "Company": 1,
    "WorkType": null,
    "ParentOperationalUnit": 0,
    "OperationalUnitName": "Office",
    "Active": true,
    "PayrollExportName": "",
    "Address": 159,
    "Contact": null,
    "RosterSortOrder": 5,
    "ShowOnRoster": true,
    "Colour": "",
    "RosterActiveHoursSchedule": null,
    "DailyRosterBudget": null,
    "OperationalUnitType": null,
    "AddressObject": {
      "Id": 159,
      "ContactName": null,
      "UnitNo": null,
      "StreetNo": null,
      "SuiteNo": null,
      "PoBox": null,
      "Street1": "Random Street Collingwood City of Yarra Victoria Australia 3066",
      "Street2": null,
      "City": null,
      "State": "155",
      "Postcode": null,
      "Country": 13,
      "Phone": null,
      "Notes": null,
      "Format": null,
      "Saved": null,
      "Creator": 1,
      "Created": "2023-05-25T09:48:28+08:00",
      "Modified": "2023-05-25T09:48:28+08:00",
      "Print": "Random Street Collingwood City of Yarra Victoria Australia 3066\n"
    },
    "CompanyCode": "0A1",
    "CompanyName": "Dcode Melbourne",
    "CompanyAddress": 159,
    "_DPMetaData": {
      "System": "OperationalUnit",
      "CreatorInfo": {
        "Id": 1,
        "DisplayName": "Dcode Agency",
        "EmployeeProfile": 1,
        "Employee": 1,
        "Photo": "https://d11hmzhsuwuq9f.cloudfront.net/my/avatar?name=D+A&width=135&height=135",
        "Pronouns": 0,
        "CustomPronouns": null
      },
      "AddressObject": {
        "Id": 159,
        "ContactName": null,
        "UnitNo": null,
        "StreetNo": null,
        "SuiteNo": null,
        "PoBox": null,
        "Street1": "Random Street Collingwood City of Yarra Victoria Australia 3066",
        "Street2": null,
        "City": null,
        "State": "155",
        "Postcode": null,
        "Country": 13,
        "Phone": null,
        "Notes": null,
        "Format": null,
        "Saved": null,
        "Creator": 1,
        "Created": "2023-05-25T09:48:28+08:00",
        "Modified": "2023-05-25T09:48:28+08:00",
        "Print": "Random Street Collingwood City of Yarra Victoria Australia 3066\n"
      },
      "Geo": null
    }
  },
  {
    "Id": 18,
    "Creator": 1,
    "Created": "2023-05-25T11:47:07+08:00",
    "Modified": "2023-05-25T13:11:47+08:00",
    "Company": 2,
    "WorkType": null,
    "ParentOperationalUnit": 0,
    "OperationalUnitName": "Suburb",
    "Active": true,
    "PayrollExportName": "",
    "Address": 160,
    "Contact": null,
    "RosterSortOrder": 0,
    "ShowOnRoster": true,
    "Colour": "",
    "RosterActiveHoursSchedule": null,
    "DailyRosterBudget": null,
    "OperationalUnitType": null,
    "AddressObject": {
      "Id": 160,
      "ContactName": null,
      "UnitNo": null,
      "StreetNo": null,
      "SuiteNo": null,
      "PoBox": null,
      "Street1": "Saint Georges Terrace Perth City of Perth Western Australia Australia 6000",
      "Street2": null,
      "City": null,
      "State": "156",
      "Postcode": null,
      "Country": 13,
      "Phone": null,
      "Notes": null,
      "Format": null,
      "Saved": null,
      "Creator": 1,
      "Created": "2023-05-25T09:48:28+08:00",
      "Modified": "2023-05-25T09:48:28+08:00",
      "Print": "Saint Georges Terrace Perth City of Perth Western Australia Aust"
    },
    "CompanyCode": "dco",
    "CompanyName": "dcode perth",
    "CompanyAddress": 160,
    "_DPMetaData": {
      "System": "OperationalUnit",
      "CreatorInfo": {
        "Id": 1,
        "DisplayName": "Dcode Agency",
        "EmployeeProfile": 1,
        "Employee": 1,
        "Photo": "https://d11hmzhsuwuq9f.cloudfront.net/my/avatar?name=D+A&width=135&height=135",
        "Pronouns": 0,
        "CustomPronouns": null
      },
      "AddressObject": {
        "Id": 160,
        "ContactName": null,
        "UnitNo": null,
        "StreetNo": null,
        "SuiteNo": null,
        "PoBox": null,
        "Street1": "Saint Georges Terrace Perth City of Perth Western Australia Australia 6000",
        "Street2": null,
        "City": null,
        "State": "156",
        "Postcode": null,
        "Country": 13,
        "Phone": null,
        "Notes": null,
        "Format": null,
        "Saved": null,
        "Creator": 1,
        "Created": "2023-05-25T09:48:28+08:00",
        "Modified": "2023-05-25T09:48:28+08:00",
        "Print": "Saint Georges Terrace Perth City of Perth Western Australia Aust"
      },
      "Geo": null
    }
  },
  {
    "Id": 19,
    "Creator": 1,
    "Created": "2023-05-25T11:47:17+08:00",
    "Modified": "2023-05-25T11:47:17+08:00",
    "Company": 3,
    "WorkType": null,
    "ParentOperationalUnit": 0,
    "OperationalUnitName": "Office",
    "Active": true,
    "PayrollExportName": "",
    "Address": 161,
    "Contact": null,
    "RosterSortOrder": 5,
    "ShowOnRoster": true,
    "Colour": "",
    "RosterActiveHoursSchedule": null,
    "DailyRosterBudget": null,
    "OperationalUnitType": null,
    "AddressObject": {
      "Id": 161,
      "ContactName": null,
      "UnitNo": null,
      "StreetNo": null,
      "SuiteNo": null,
      "PoBox": null,
      "Street1": "58 P. Quốc Tử Giám, Văn Miếu, Đống Đa, Hà Nội, Vietnam",
      "Street2": null,
      "City": null,
      "State": "Hà Nội",
      "Postcode": null,
      "Country": 231,
      "Phone": null,
      "Notes": null,
      "Format": null,
      "Saved": null,
      "Creator": 1,
      "Created": "2023-05-25T09:48:28+08:00",
      "Modified": "2023-05-25T09:48:28+08:00",
      "Print": "58 P. Quốc Tử Giám, Văn Miếu, Đống Đa, Hà Nội, Vietnam\n"
    },
    "CompanyCode": "dco",
    "CompanyName": "dcode vietnam",
    "CompanyAddress": 161,
    "_DPMetaData": {
      "System": "OperationalUnit",
      "CreatorInfo": {
        "Id": 1,
        "DisplayName": "Dcode Agency",
        "EmployeeProfile": 1,
        "Employee": 1,
        "Photo": "https://d11hmzhsuwuq9f.cloudfront.net/my/avatar?name=D+A&width=135&height=135",
        "Pronouns": 0,
        "CustomPronouns": null
      },
      "AddressObject": {
        "Id": 161,
        "ContactName": null,
        "UnitNo": null,
        "StreetNo": null,
        "SuiteNo": null,
        "PoBox": null,
        "Street1": "58 P. Quốc Tử Giám, Văn Miếu, Đống Đa, Hà Nội, Vietnam",
        "Street2": null,
        "City": null,
        "State": "Hà Nội",
        "Postcode": null,
        "Country": 231,
        "Phone": null,
        "Notes": null,
        "Format": null,
        "Saved": null,
        "Creator": 1,
        "Created": "2023-05-25T09:48:28+08:00",
        "Modified": "2023-05-25T09:48:28+08:00",
        "Print": "58 P. Quốc Tử Giám, Văn Miếu, Đống Đa, Hà Nội, Vietnam\n"
      },
      "Geo": null
    }
  }
]
```

### CODE REVIEW

**Comment by SonOfHarris** [comment]
Thanks @lionslair for the changes. Feel free to modify your notes just to make sure no sensitive information has been exposed in your example.

It's been a while since the `@property` list was updated based on the results of the schema returned via the resource/INFO endpoints. I can see that `WorkType` and `OperationalUnitType` are present in the schema so happy to accept those.

The `CompanyName` and `CompanyCode` values are not within the schema or official documentation. I've investigated our sandbox environment and noticed that they do not come through in any of our `OperationalUnit` requests, so I feel this is something specific to how your environment has been configured. As the values are not documented or present in the schema I'm not comfortable adding those properties.

Could you please remove the `$companyName` and `$companyCode` properties. Happy to merge after that.

Before the next official release I'll update the tests and make some tooling to regenerate the `@property` tags based on the schema, as I'm sure there would be some missing in other resources.

**Comment by lionslair** [comment]
None of it is sensitive I already did replacements on the bits that are but wanted to show the data provided.

I can confirm those fields are returned even though not documented. I have run this from their API explorer on their site.

https://developer.deputy.com/deputy-docs/reference/getoperationalunits
Screenshot from 2023-06-06 09-32-39

**Comment by SonOfHarris** [comment]
I understand that within your environment the values are shown but the position of this library is to reflect only what is explicitly documented by Deputy. If Deputy updates the schema or their documentation to add these company fields I'll be happy to add the properties.

The alternative is a slippery slope where the library says there should be a property or relationship that may not actually exist for other developers.

I'm sorry that I can't accept those specific changes but I do need to draw a line somewhere.

**Comment by SonOfHarris** [comment]
The way this library knows what properties do exist is dynamically based on the schema returned by the resource/INFO endpoints. There are also ways of extending these schemas via the configuration array used to create the wrapper but no documentation has been written on how this is done.

So it might be possible to add customisations specific to your environment. The only downside of this approach is that whilst the library would understand the property exists, the code wouldn't have the `@property` tag to provide support in IDEs.

**Comment by lionslair** [comment]
Sorry wrong screenshot

https://developer.deputy.com/deputy-docs/reference/getoperationalunits
Screenshot from 2023-06-06 09-32-39

I'm adding or configuring anything custom BTW

**Comment by SonOfHarris** [comment]
Thanks @lionslair. I've been looking deeper and have now seen those company properties in the raw `OperationalUnit` response. So I apologise for not delving deeper before my initial response.

Thinking more about it, they are properties of the `Company` resource that are being exposed within the `OperationalUnit` resource. So I'm still not comfortable with adding them to the `OperationalUnit` model as they are not documented or defined. The company values should instead be accessed via the `OperationalUnit->companyObject` object.

If you want to retrieve both `OperationalUnit` and `Company` information in the same request (avoiding N+1 problems) then use the `joinWith` function on the query:

```
$units = Wrapper::getInstance()
    ->findOperationalUnits()
    ->joinWith('companyObject')
    ->all();
foreach ($units as $unit) {
    echo "{$unit->id} - {$unit->displayName} -- {$unit->companyObject->displayName}" . PHP_EOL;
}
```

There's lots of changes soon to be released as part of this investigation, including a CLI tool for debugging, so I'll accept this request and then remove the company properties before the next release.

**Comment by lionslair** [comment]
Ok thanks. yeah. I am storing them locally more as reference in case it changes.  Was not sure why it was there.

**Pull request merged**
